client:
  contributeUrl: https://docs.google.com/document/d/1tDlWfX2TtczI5IHLmffY4LPya1J1Z9ZWHW4pYlD8toM/edit?usp=sharing
  apiBaseUrl: api
  versionNumber: 2.1.0
  versionName: erik doe rustig
  repositoryUrl: https://github.com/villermen/soundboard
