client:
  contributeUrl: https://docs.google.com/document/d/1tDlWfX2TtczI5IHLmffY4LPya1J1Z9ZWHW4pYlD8toM/edit?usp=sharing
  apiBaseUrl: api
  versionNumber: 2.2.0
  versionName: how about no, you crazy dutch bastard
  versionSampleId: 8ff805da
  repositoryUrl: https://github.com/villermen/soundboard
