server:
  slim:
    settings:
      displayErrorDetails: true

  router:
    routes:
      samples_list:
        path: /samples
        controller: Villermen\Soundboard\Controllers\SamplesController
        action: listAction
        methods: [ get ]
      telegram:
        path: /telegram
        controller: Villermen\Soundboard\Controllers\TelegramController
        action: webhookAction
        methods: [ post ]
