server:
  sampleLocation: ../../samples

  slim:
    settings:
      displayErrorDetails: true

  router:
    routes:
      samples_list:
        path: /samples
        controller: Villermen\Soundboard\Controllers\SamplesController
        action: listAction
        methods: [ get ]

      samples_get:
        path: /samples/{file:.+}
        controller: Villermen\Soundboard\Controllers\SamplesController
        action: getAction
        methods: [ get ]
