soundboard:
  sampleLocation: ../../public/samples
  publicSampleLocation: samples

slim:
  settings:
    displayErrorDetails: true

router:
  routes:
    samples_list:
      path: /samples
      controller: Villermen\Soundboard\Controllers\SamplesController
      action: listAction
      methods: [ get ]
